In [646]:
import pandas as pd
import math
import numpy as np
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import f1_score,accuracy_score,r2_score,mean_squared_error
import warnings
warnings.filterwarnings("ignore")

In [647]:
train=pd.read_csv(r"C:\Users\amany\Desktop\Black_Friday_Sales_prediction\train.csv")
test=pd.read_csv(r"C:\Users\amany\Desktop\Black_Friday_Sales_prediction\test.csv")
original_train = train.copy()
original_test = test.copy()


In [648]:
print(train.shape)
train.isnull().sum()

(550068, 12)


User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [649]:
# train['Age'] = train['Age'].astype('category')
# dummy = pd.get_dummies(train['Age'])
# train = pd.concat((train,dummy),axis=1)
# train=train.drop(['Age','55+','26-35','36-45','46-50','51-55','18-25',],axis=1)
# train=train.rename(columns={"0-17":"Age"})


train.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [650]:
train["Product_Category_2"].fillna(train["Product_Category_2"].median(), inplace=True)
train["Product_Category_3"].fillna(train["Product_Category_3"].median(), inplace=True)

#test

test["Product_Category_2"].fillna(train["Product_Category_2"].median(), inplace=True)
test["Product_Category_3"].fillna(train["Product_Category_3"].median(), inplace=True)

In [651]:
train.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [652]:
test.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
dtype: int64

In [653]:
train=train.drop('Product_ID',axis=1)
test=test.drop('Product_ID',axis=1)

for label, content in train.items():
    if pd.api.types.is_string_dtype(content):
        print(label)

Gender
Age
City_Category
Stay_In_Current_City_Years


In [654]:
X=train.drop('Purchase',axis=1)
y=train['Purchase']

In [655]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((440054, 10), (440054,), (110014, 10), (110014,))

In [656]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Age", "Gender", "City_Category", "Stay_In_Current_City_Years"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot, 
                                 categorical_features)],
                                remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X.shape

(550068, 23)

In [657]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  1.0  0.0   
1       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  1.0  0.0   
2       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  1.0  0.0   
3       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  1.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
550063  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  1.0  0.0  0.0   
550064  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0   
550065  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
550066  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  ...  0.0  1.0  0.0   
550067  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   

         16         17    18   19    20    21    22  
0       0.0  1000001.0  10.0  0.0   3.0   9.0  14.0  
1       0.0  1000001.0  10.0  0.0   1.0   6.0  14.0  
2       0.0  1000001.0  10.0  0.0  12.0   9.0  14.0  
3       0.0  1000001.0  10.0  0.0  12.0  14.0  14.0  
4       1.0  1000002.0  16.0  0.0   8.0   9.0  14.0  
...     ...        ...   ...  ...   ...   ...   ...  
550063  0.0  1006033.0  13.0  1.0  20.0   9.0  14.0  
550064  0.0  1006035.0   1.0  0.0  20.0   9.0  14.0  
550065  1.0  1006036.0  15.0  1.0  20.0   9.0  14.0  
550066  0.0  1006038.0   1.0  0.0  20.0   9.0  14.0  
550067  1.0  1006039.0   0.0  1.0  20.0   9.0  14.0  

[550068 rows x 23 columns]

In [658]:
X_train,X_test,y_train,y_test = train_test_split(transformed_X,y, test_size=0.2)

In [659]:
# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor(n_jobs=-1,
#                               random_state=42,
#                               min_samples_split=90,
#                               min_samples_leaf=6,
#                               n_estimators=100,
#                               verbose=True)
# model.fit(X_train, y_train)

%time
from sklearn.model_selection import RandomizedSearchCV

# # Different RandomForestRegressor hyperparameters
rf_grid = {"n_estimators":np.arange(10,100,10),
            "max_depth": [None,3,5,10],
            "min_samples_split":np.arange(2,20,2),
            "min_samples_leaf":np.arange(1,20,2),
            "max_features":[0.5,1,"sqrt","auto"]}

 # Instantiate RandomizedSearchCV
model = RandomizedSearchCV(RandomForestRegressor(n_jobs=-1,
                                                     random_state=42),
                               param_distributions=rf_grid,
                               n_iter=200,
                               cv=5,
                               verbose=True)

 # Fit the RandomizedSearchCV model
model.fit(X_train,y_train)

Wall time: 0 ns
Fitting 5 folds for each of 200 candidates, totalling 1000 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 1000 out of 1000 | elapsed: 309.8min finished


RandomizedSearchCV(cv=5, error_score='raise-deprecating',
                   estimator=RandomForestRegressor(bootstrap=True,
                                                   criterion='mse',
                                                   max_depth=None,
                                                   max_features='auto',
                                                   max_leaf_nodes=None,
                                                   min_impurity_decrease=0.0,
                                                   min_impurity_split=None,
                                                   min_samples_leaf=1,
                                                   min_samples_split=2,
                                                   min_weight_fraction_leaf=0.0,
                                                   n_estimators='warn',
                                                   n_jobs=-1, oob_score=False,
                                                   random_state...


In [660]:
lin_pred = model.predict(X_test)
lin_pred

array([14195.7167769 ,  6688.53810529,  6213.28960764, ...,
        6519.20905628, 13508.26412234, 20195.62688458])

In [673]:
m=mean_squared_error(y_test,lin_pred)
rmse = math.sqrt(m)
rmse

2828.9834373926124

In [665]:
#Applying on TEST DATA

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Age", "Gender", "City_Category", "Stay_In_Current_City_Years"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot, 
                                 categorical_features)],
                                remainder = "passthrough")
transformed_X1 = transformer.fit_transform(test)
transformed_X1

array([[ 0.,  0.,  0., ...,  1., 11., 14.],
       [ 0.,  0.,  1., ...,  3.,  5., 14.],
       [ 0.,  0.,  0., ...,  5., 14., 14.],
       ...,
       [ 0.,  0.,  1., ...,  1.,  5., 12.],
       [ 0.,  0.,  0., ..., 10., 16., 14.],
       [ 0.,  0.,  0., ...,  4.,  5., 14.]])

In [666]:
pd.DataFrame(transformed_X1)

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0       0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  0.0   
1       0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
2       0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
3       0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
4       0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
233594  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
233595  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
233596  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
233597  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
233598  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   

         16         17    18   19    20    21    22  
0       0.0  1000004.0   7.0  1.0   1.0  11.0  14.0  
1       0.0  1000009.0  17.0  0.0   3.0   5.0  14.0  
2       1.0  1000010.0   1.0  1.0   5.0  14.0  14.0  
3       1.0  1000010.0   1.0  1.0   4.0   9.0  14.0  
4       0.0  1000011.0   1.0  0.0   4.0   5.0  12.0  
...     ...        ...   ...  ...   ...   ...   ...  
233594  1.0  1006036.0  15.0  1.0   8.0   9.0  14.0  
233595  1.0  1006036.0  15.0  1.0   5.0   8.0  14.0  
233596  1.0  1006036.0  15.0  1.0   1.0   5.0  12.0  
233597  1.0  1006037.0   1.0  0.0  10.0  16.0  14.0  
233598  1.0  1006039.0   0.0  1.0   4.0   5.0  14.0  

[233599 rows x 23 columns]

In [667]:
lin_pred_test = model.predict(X_test)
lin_pred_test

array([14195.7167769 ,  6688.53810529,  6213.28960764, ...,
        6519.20905628, 13508.26412234, 20195.62688458])

In [669]:
sub=pd.read_csv(r"C:\Users\amany\Desktop\blackresult.csv")

In [670]:
sub["Purchase"]=lin_pred_test
sub["User_ID"]=original_test["User_ID"]
sub["Product_ID"]=original_test["Product_ID"]

In [671]:
sub.to_csv('Black_Friday_Result.csv', index=False)

In [672]:
sub

Purchase  User_ID Product_ID
0       14195.716777  1000004  P00128942
1        6688.538105  1000009  P00113442
2        6213.289608  1000010  P00288442
3        6128.326079  1000010  P00145342
4       13782.908945  1000011  P00053842
...              ...      ...        ...
110009   5555.524191  1001357  P00258942
110010   7647.800099  1001357  P00196842
110011   6519.209056  1001358  P00183242
110012  13508.264122  1001359  P00117942
110013  20195.626885  1001360  P00214142

[110014 rows x 3 columns]